server:
  port: 0

spring:
  application:
    name: room-service

  config:
    import: optional:configserver:http://config-service:8888

  cloud:
    config:
      name: room-service

  data:
    redis:
      port: 6379
      host: redis

    mongodb:
      uri: mongodb://root:1234@mongodb:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.2
      database: socat

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/rooms
    username: postgres
    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
springdoc:
  swagger-ui:
    operations-sorter: method
