server:
  port: 0

spring:
  application:
    name: room-service
  data:
    redis:
      port: 6379
      host: localhost

    mongodb:
      uri: mongodb://root:1234@localhost:27017/socat?authSource=admin

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
