server:
  port: 0

spring:
  application:
    name: chat-service

  config:
    import: optional:configserver:http://config-service:8888

  cloud:
    config:
      name: chat-service

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
    suffix: .ftl

  data:
    redis:
      port: 6379
      host: redis

    mongodb:
      uri: mongodb://root:1234@mongodb:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.2
      database: socat



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh,metrics,prometheus
