server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 1234

  cloud:
    config:
      server:
        git:
          uri: https://github.com/padosol/Socat.git
          search-paths: config
          default-label: main

encrypt:
  key-store:
    location: file:/apiEncryptionKey.jks
    password: socat1234
    alias: apiEncryptionKey

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh


