server:
  port: 0

spring:
  application:
    name: room-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name: room-service

  data:
    redis:
      port: 6379
      host: localhost

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/msa
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh,env

logging:
  level:
    com.room.roomservice.domain.room.client: DEBUG
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
  pattern:
    correlation: '%5p [${spring.application.name:}, %X{traceId:-},%X{spanId-}]'

springdoc:
  swagger-ui:
    operations-sorter: method
