server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/padosol/socat-config.git
          default-label: main
          username: padosol

encrypt:
  key-store:
    location: /apiEncryptionKey.jks
    password: socat1234
    alias: apiEncryptionKey

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh


