server:
  port: 8888

spring:
  application:
    name: chat-service

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
    suffix: .ftl


