server:
  port: 0

spring:
  application:
    name: chat-service

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      name: socat

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false
    suffix: .ftl

  data:
    redis:
      port: 6379
      host: localhost

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#jwt:
#  secret: sackjrmlqwkhjrcklqcqwejrhcnqewjklrhcuwienhrcjkwerchnwlq
#  access-token-expired-time: 3600000 # 시간
#  refresh_token_expired_time: 604800000 # 하루
#  access_token_name: access_token
#  refresh_token_name: refresh_token
