server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/padosol/Socat.git
          default-label: master
          username: <github-id>
          password: <github-access-token>

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh

encrypt:
  key-store:
    # location: file:///${user.home}/Desktop/keystore/apiEncryptionKey.jks
    location: file:/apiEncryptionKey.jks
    password: socat1234
    alias: apiEncryptionKey
