server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: native

  rabbitmq:
    host: rabbitmq
#    host: 127.0.0.1
    port: 5672
    username: admin
    password: 1234

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\hzyan\Desktop\socat\config
        git:
          uri: https://github.com/padosol/Socat.git
          search-paths: config
          default-label: main

encrypt:
  key-store:
#    location: file:///${user.home}/Desktop/keystore/apiEncryptionKey.jks
    location: file:/apiEncryptionKey.jks
    password: socat1234
    alias: apiEncryptionKey

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh


